DOCSP-26393: FAQ entry for NoClassDefFoundError (#425)
* DOCSP-26393: FAQ entry for NoClasDefFoundError

(cherry picked from commit daee823b1a8d72c720e1b479b939decb17f4b4f6)